### PR TITLE
feature/refactor: aggregated improvements

### PR DESCRIPTION
**Pull request by eimaam**
This PR : 
> Redesign `How-to` Section 
> Refactored Components
> Fix some types
> Added Prettier formatting script 

Go through the changes and let me know if it looks good enough or you have suggestion(s)

### CODE REVIEW

**Review by teoh4770 — APPROVED** [review]

**Review by teoh4770 — COMMENTED** [review]
currently this commit here causes a bug, let me review it carefully to see what's causing this

**Comment by teoh4770** [comment]
Thanks @eimaam, those are good refactor and additions.
I will merge it and fix some of the issue.
Thanks agian

**Comment by eimaam** [comment]
> Thanks @eimaam, those are good refactor and additions. I will merge it and fix some of the issues regarding the logic and styling Thanks again

Sounds good @teoh4770 
You're welcome!

**Pull request merged**
